# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcsg324-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir E:/Vivado/homework/project_1/project_1.cache/wt [current_project]
set_property parent.project_path E:/Vivado/homework/project_1/project_1.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
read_verilog -library xil_defaultlib E:/Vivado/homework/project_1/project_1.srcs/sources_1/new/add_4.v
synth_design -top add_4 -part xc7a35tcsg324-1
write_checkpoint -noxdef add_4.dcp
catch { report_utilization -file add_4_utilization_synth.rpt -pb add_4_utilization_synth.pb }
